using System.Diagnostics;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using SQLitePCL;
namespace RoomDesk.Core;
public sealed record StorageInfo(string DatabasePath,string JournalMode,long Synchronous,double DatabaseMb,double WalMb,double WorkingSetMb,string? LastBackup,string? MaintenanceError);
public sealed partial class BoardStore
{
    private readonly SemaphoreSlim maintenanceGate=new(1,1);
    public string? MaintenanceError {get;private set;}
    public string? LastAutomaticBackup {get;private set;}
    public async Task<StorageInfo> ReadStorageInfoAsync()
    {
        await using var db=Open();var connection=db.Database.GetDbConnection();
        async Task<object?> Pragma(string sql){using var command=connection.CreateCommand();command.CommandText=sql;return await command.ExecuteScalarAsync();}
        static double Size(string path)=>File.Exists(path)?Math.Round(new FileInfo(path).Length/1048576d,2):0;
        return new(DatabasePath,(await Pragma("PRAGMA journal_mode"))?.ToString()??"",Convert.ToInt64(await Pragma("PRAGMA synchronous")),Size(DatabasePath),Size(DatabasePath+"-wal"),Math.Round(Process.GetCurrentProcess().WorkingSet64/1048576d,1),LastAutomaticBackup,MaintenanceError);
    }
    public async Task RunMaintenanceLoopAsync(CancellationToken cancellation)
    {
        try{await Task.Delay(TimeSpan.FromSeconds(15),cancellation);while(!cancellation.IsCancellationRequested){await MaintainAsync(cancellation);await Task.Delay(TimeSpan.FromMinutes(15),cancellation);}}
        catch(OperationCanceledException)when(cancellation.IsCancellationRequested){}
    }
    public async Task MaintainAsync(CancellationToken cancellation=default)
    {
        if(!await maintenanceGate.WaitAsync(0,cancellation))return;
        try{
            var folder=Path.Combine(Path.GetDirectoryName(DatabasePath)!,"automatic-backups",Path.GetFileName(DatabasePath));Directory.CreateDirectory(folder);
            var path=Path.Combine(folder,$"auto-{DateTime.Now:yyyyMMdd}.db");
            if(!File.Exists(path)){
                await CopyOnlineBackupAsync(path,cancellation);LastAutomaticBackup=path;
            }else LastAutomaticBackup=path;
            // Only rotate files generated by this mechanism; manual backups and history are untouched.
            foreach(var old in Directory.GetFiles(folder,"auto-????????.db").OrderDescending().Skip(7))File.Delete(old);
            var cache=Path.Combine(Path.GetDirectoryName(DatabasePath)!,"export-cache");
            if(Directory.Exists(cache))foreach(var file in Directory.GetFiles(cache,"*.tmp"))if(File.GetLastWriteTimeUtc(file)<DateTime.UtcNow.AddDays(-1)){try{File.Delete(file);}catch(IOException){}}
            await using var db=Open();
            await db.Database.ExecuteSqlRawAsync("PRAGMA wal_checkpoint(PASSIVE); PRAGMA analysis_limit=400; PRAGMA optimize;",cancellation);
            MaintenanceError=null;
        }catch(OperationCanceledException)when(cancellation.IsCancellationRequested){throw;}
        catch(Exception ex){MaintenanceError=ex.Message;}
        finally{maintenanceGate.Release();}
    }
    private async Task CopyOnlineBackupAsync(string path,CancellationToken cancellation=default)
    {
                var temp=path+".partial";
                if(File.Exists(temp))File.Delete(temp);
                try{
                    using(var source=new SqliteConnection(new SqliteConnectionStringBuilder{DataSource=DatabasePath,Mode=SqliteOpenMode.ReadOnly,Pooling=false}.ToString()))
                    using(var destination=new SqliteConnection(new SqliteConnectionStringBuilder{DataSource=temp,Pooling=false}.ToString())){
                        await source.OpenAsync(cancellation);await destination.OpenAsync(cancellation);
                        using(var configure=source.CreateCommand()){configure.CommandText="PRAGMA cache_size=-1024; PRAGMA mmap_size=0";await configure.ExecuteNonQueryAsync(cancellation);}
                        using(var configure=destination.CreateCommand()){configure.CommandText="PRAGMA synchronous=FULL; PRAGMA fullfsync=ON; PRAGMA cache_size=-1024";await configure.ExecuteNonQueryAsync(cancellation);}
                        using(var backup=raw.sqlite3_backup_init(destination.Handle,"main",source.Handle,"main")){
                            var started=Stopwatch.StartNew();
                            while(true){cancellation.ThrowIfCancellationRequested();var code=raw.sqlite3_backup_step(backup,128);if(code==raw.SQLITE_DONE)break;if(code!=raw.SQLITE_OK&&code!=raw.SQLITE_BUSY&&code!=raw.SQLITE_LOCKED)throw new IOException("自动备份失败，SQLite 状态 "+code);if(started.Elapsed>TimeSpan.FromMinutes(5))throw new IOException("自动备份超时，将稍后重试。");await Task.Delay(5,cancellation);}
                        }
                        using var check=destination.CreateCommand();check.CommandText="PRAGMA quick_check";if((await check.ExecuteScalarAsync(cancellation))?.ToString()!="ok")throw new IOException("自动备份完整性检查失败。");
                    }
                    File.Move(temp,path);
                }finally{if(File.Exists(temp))File.Delete(temp);}
    }

}
