<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF><EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>RoomDesk</AssemblyName>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../Core/Core.csproj" /></ItemGroup>
</Project>
